import type { RawArticle } from "@/lib/types";

export const DEMO_ARTICLES: RawArticle[] = [
  // ─── ECONOMY (20 articles) ─────────────────────────────────────────────────
  {
    externalId: "demo_001",
    title: "RON95 Subsidy Rationalisation: Government Finalising RM4,000 Household Income Threshold",
    summary:
      "The government is in final stages of setting a RM4,000 monthly household income threshold for RON95 petrol subsidy eligibility, with implementation targeted for Q3 2025. Households earning above the threshold will pay market-rate prices of approximately RM3.50 per litre at the pump starting from August.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/news/nation/2026/05/16/ron95-subsidy-threshold-finalised",
    topic: "Economy",
    publishedAt: "2026-05-16T08:30:00+08:00",
  },
  {
    externalId: "demo_002",
    title: "Ringgit Strengthens to 4.38 Against USD on Strong March Trade Data",
    summary:
      "The Malaysian ringgit gained 0.8% against the US dollar to close at 4.38, buoyed by stronger-than-expected March trade surplus data of RM18.2 billion. Analysts at Maybank IB note the currency could test 4.30 support if export momentum continues through Q2 2025.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/ringgit-strengthens-438-usd-march-trade-data",
    topic: "Economy",
    publishedAt: "2026-05-16T09:15:00+08:00",
  },
  {
    externalId: "demo_003",
    title: "Bank Negara Holds OPR at 3.00% — Mortgage and Car Loan Rates Unchanged",
    summary:
      "Bank Negara Malaysia kept the Overnight Policy Rate at 3.00% for the fourth consecutive meeting, citing stable inflation at 1.8% and resilient domestic growth of 4.8%. Homeowners on variable-rate mortgages will see no change to their monthly repayments, with the next review scheduled for July 2025.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2436001",
    topic: "Economy",
    publishedAt: "2026-05-16T10:00:00+08:00",
  },
  {
    externalId: "demo_004",
    title: "Malaysia GDP Grows 4.8% in Q1 2025, Beating Analyst Forecasts of 4.2%",
    summary:
      "Malaysia's economy expanded 4.8% year-on-year in the first quarter of 2025, outpacing the 4.2% consensus forecast driven by a 7.1% surge in services sector output. The strong performance was underpinned by RM30 billion in approved FDI and robust domestic consumption, Department of Statistics Malaysia reported.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/business/2026/05/16/malaysia-gdp-q1-2025-beats-forecast",
    topic: "Economy",
    publishedAt: "2026-05-16T11:30:00+08:00",
  },
  {
    externalId: "demo_005",
    title: "Inflation Drops to 1.8% in April — Food Prices Finally Easing After 14 Months",
    summary:
      "Malaysia's Consumer Price Index rose just 1.8% year-on-year in April 2025, down from 2.1% in March, as vegetable prices fell 4.2% and chicken prices stabilised at RM9.50/kg following supply chain improvements. The Department of Statistics attributed the cooling to higher domestic food production and easing global commodity prices.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/money/2026/05/16/inflation-18pct-april-food-prices-ease",
    topic: "Economy",
    publishedAt: "2026-05-15T08:00:00+08:00",
  },
  {
    externalId: "demo_006",
    title: "SST Expansion Confirmed: Digital Services, Streaming Subscriptions Taxed from July 2025",
    summary:
      "The Royal Malaysian Customs Department confirmed that Sales and Services Tax will expand to cover digital streaming services, cloud storage, and online platforms from 1 July 2025. Netflix, Spotify, and similar services will add a 6% SST charge to Malaysian subscribers, increasing a RM55 monthly plan to RM58.30.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/business/business-news/2026/05/15/sst-expansion-digital-services-july",
    topic: "Economy",
    publishedAt: "2026-05-15T09:45:00+08:00",
  },
  {
    externalId: "demo_007",
    title: "EPF Declares 6.1% Dividend for Conventional Savings in 2024 — Total Payout RM62 Billion",
    summary:
      "The Employees Provident Fund announced a 6.1% dividend for conventional savings and 5.9% for shariah savings for the year 2024, representing a total payout of RM62 billion to 16 million active members. A member with RM100,000 in savings will receive RM6,100 in dividends, credited automatically by end of March 2025.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2436120",
    topic: "Economy",
    publishedAt: "2026-05-15T10:30:00+08:00",
  },
  {
    externalId: "demo_008",
    title: "Weekly Petrol Price: RON95 Fixed at RM2.05, RON97 Dips 10 Sen to RM3.38",
    summary:
      "The weekly fuel price update shows RON95 remains fixed at RM2.05 per litre under the targeted subsidy framework, while RON97 fell 10 sen to RM3.38 and diesel eased to RM2.15 per litre reflecting lower global crude prices. The managed float mechanism means RON97 will continue to fluctuate weekly based on MOPS pricing.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/business/2026/05/15/weekly-petrol-price-ron97-dips",
    topic: "Economy",
    publishedAt: "2026-05-15T08:30:00+08:00",
  },
  {
    externalId: "demo_009",
    title: "Malaysia Trade Surplus Hits RM18.2 Billion in March, Exports Up 7.3%",
    summary:
      "Malaysia recorded a trade surplus of RM18.2 billion in March 2025, with exports rising 7.3% to RM136.8 billion led by electrical and electronics products which grew 12.4% year-on-year. Palm oil exports declined 5% due to weaker China demand, offsetting gains in semiconductor shipments to the United States and Europe.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/malaysia-trade-surplus-rm182b-march-exports-up",
    topic: "Economy",
    publishedAt: "2026-05-14T08:00:00+08:00",
  },
  {
    externalId: "demo_010",
    title: "Government Allocates RM2.4 Billion for SME Digital Transformation Fund",
    summary:
      "The Ministry of Entrepreneur Development and Cooperatives launched a RM2.4 billion SME Digital Transformation Fund offering grants of up to RM100,000 per business to adopt e-commerce, cloud systems, and digital payments. Applications open 1 June 2025 through the SMECorp portal, with priority given to manufacturing and retail sectors employing below 75 workers.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2436201",
    topic: "Economy",
    publishedAt: "2026-05-14T09:15:00+08:00",
  },
  {
    externalId: "demo_011",
    title: "MyDebit Transactions Surpass Credit Cards for First Time — RM8.2 Billion in March",
    summary:
      "MyDebit contactless payments hit a record RM8.2 billion in March 2025, surpassing credit card transaction values of RM7.9 billion for the first time in Malaysian payment history. Bank Negara attributed the milestone to wider merchant acceptance at over 800,000 terminals nationwide and the increase in cashless payment adoption post-pandemic.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/money/2026/05/14/mydebit-surpasses-credit-cards-first-time-record",
    topic: "Economy",
    publishedAt: "2026-05-14T11:00:00+08:00",
  },
  {
    externalId: "demo_012",
    title: "Wholesale Electricity Tariff Revision: Commercial Users Face Up to 12% Higher Bills",
    summary:
      "Tenaga Nasional Berhad's wholesale electricity tariff for commercial and industrial users will increase by an average of 8-12% from 1 July 2025, following the Energy Commission's half-yearly Imbalance Cost Pass-Through mechanism review. Small commercial premises with monthly consumption below 200 kWh are exempt from the revision.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/electricity-tariff-revision-commercial-users-12pct",
    topic: "Economy",
    publishedAt: "2026-05-13T08:30:00+08:00",
  },
  {
    externalId: "demo_013",
    title: "Kuala Lumpur Ranked 67th Most Expensive City Globally — Mercer Cost of Living Survey",
    summary:
      "Kuala Lumpur climbed four places to 67th in Mercer's 2025 Cost of Living Survey, reflecting higher rental costs and food prices compared to 2024. Despite the rise, KL remains significantly cheaper than Singapore (8th) and Hong Kong (2nd), with a monthly living cost estimate of USD 1,950 for an expatriate versus USD 4,200 in Singapore.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/news/nation/2026/05/13/kl-cost-living-67th-globally-mercer",
    topic: "Economy",
    publishedAt: "2026-05-13T09:00:00+08:00",
  },
  {
    externalId: "demo_014",
    title: "Export Growth Slows to 3.2% in April Amid US Tariff Uncertainty",
    summary:
      "Malaysia's export growth slowed to 3.2% year-on-year in April 2025, down sharply from 7.3% in March, as uncertainty around potential US tariff adjustments on Southeast Asian electronics began affecting order volumes. The Ministry of Investment, Trade and Industry said palm oil and rubber exports were hardest hit, contracting 8% combined.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/business/2026/05/13/malaysia-export-growth-slows-tariff-uncertainty",
    topic: "Economy",
    publishedAt: "2026-05-13T10:30:00+08:00",
  },
  {
    externalId: "demo_015",
    title: "TEKUN Launches RM500 Million Micro-Loan Scheme for Gig Workers and Freelancers",
    summary:
      "TEKUN Nasional opened applications for a new RM500 million micro-financing programme targeting gig economy workers, freelancers, and platform-based service providers, offering loans of RM3,000–RM50,000 at 4% annual interest. Eligible applicants must have been active in gig work for at least 12 months with documented income above RM800 per month.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2436380",
    topic: "Economy",
    publishedAt: "2026-05-12T08:00:00+08:00",
  },
  {
    externalId: "demo_016",
    title: "Import Duty Exemption on EVs Extended for Two More Years Until End of 2026",
    summary:
      "The government extended the full import duty and excise duty exemption on completely built-up electric vehicles for another two years until 31 December 2026, maintaining tax savings of RM20,000–RM80,000 per vehicle depending on the model. The extension is expected to keep EV prices competitive and support the national target of 10,000 EV sales by 2025.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/business/business-news/2026/05/12/ev-import-duty-exemption-extended-2026",
    topic: "Economy",
    publishedAt: "2026-05-12T09:30:00+08:00",
  },
  {
    externalId: "demo_017",
    title: "Malaysia Household Debt Ratio Eases to 84.2% of GDP — Bank Negara Report",
    summary:
      "Malaysia's household debt-to-GDP ratio declined slightly to 84.2% in 2024 from 85.1% the previous year, driven by stronger GDP growth rather than a reduction in absolute borrowing levels, Bank Negara's Financial Stability Report revealed. Mortgage loans still account for 58% of total household debt at RM1.4 trillion, though average debt-service ratios remain manageable at 38%.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/household-debt-84pct-gdp-bank-negara-2024",
    topic: "Economy",
    publishedAt: "2026-05-11T08:00:00+08:00",
  },
  {
    externalId: "demo_018",
    title: "FDI Inflows Hit RM30 Billion in Q1 2025, Led by Data Centre and Semiconductor Investments",
    summary:
      "Malaysia attracted RM30 billion in approved foreign direct investment in Q1 2025, the highest first-quarter FDI on record, with the services sector accounting for RM18.4 billion led by data centre commitments from Google, Microsoft, and ByteDance. The manufacturing sector drew RM9.2 billion primarily in semiconductor and electrical components from US and Taiwan-based firms.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2436510",
    topic: "Economy",
    publishedAt: "2026-05-11T10:00:00+08:00",
  },
  {
    externalId: "demo_019",
    title: "Budget 2026 Planning Begins: Healthcare, Digital Infrastructure, and Housing Top Lobby List",
    summary:
      "The Ministry of Finance has begun early consultations for Budget 2026 with over 40 industry associations and NGOs submitting proposals, with healthcare funding, 5G infrastructure expansion, and affordable housing topping the request list. The budget is expected to be tabled in Parliament on 17 October 2025 with a projected expenditure of RM430 billion.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/budget-2026-planning-consultations-begin-healthcare-housing",
    topic: "Economy",
    publishedAt: "2026-05-10T09:00:00+08:00",
  },
  {
    externalId: "demo_020",
    title: "Palm Oil Price Falls 3.8% on Weak China Demand — Planters Warn of Margin Squeeze",
    summary:
      "Crude palm oil futures on Bursa Malaysia dropped 3.8% to RM3,820 per tonne after China's Palm Oil Import Association signalled a 15% reduction in Q2 purchase volumes amid oversupply concerns in domestic stockpiles. Plantation companies including IOI Corp and Sime Darby Plantation warned of earnings pressure if prices stay below RM3,800 for more than six weeks.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/business/business-news/2026/05/10/palm-oil-price-drops-china-demand",
    topic: "Economy",
    publishedAt: "2026-05-10T10:30:00+08:00",
  },

  // ─── MALAYSIAN POLITICS (15 articles) ────────────────────────────────────────
  {
    externalId: "demo_021",
    title: "PM Anwar Announces New Anti-Corruption Task Force with Royal Backing and Special Powers",
    summary:
      "Prime Minister Datuk Seri Anwar Ibrahim unveiled a 15-member Anti-Corruption Task Force with royal endorsement, granting it access to all government procurement records and the power to refer cases directly to the Public Prosecutor without going through ministry channels. The task force will initially focus on contracts above RM10 million awarded between 2018 and 2023.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/malaysia/2026/05/16/pm-anwar-anti-corruption-taskforce-royal-backing",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-16T14:00:00+08:00",
  },
  {
    externalId: "demo_022",
    title: "Parliament Passes Amended Anti-Money Laundering Act with Heavier Corporate Penalties",
    summary:
      "Parliament passed amendments to the Anti-Money Laundering, Anti-Terrorism Financing and Proceeds of Unlawful Activities Act 2001, raising maximum corporate fines from RM3 million to RM20 million per offence and introducing mandatory conviction reporting. The amendments bring Malaysia into compliance with FATF's 2024 recommendations and take effect 1 August 2025.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2436605",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-16T15:30:00+08:00",
  },
  {
    externalId: "demo_023",
    title: "Selangor Launches RM500 Million Affordable Housing Initiative — 8,000 Units by 2027",
    summary:
      "Menteri Besar Datuk Seri Amirudin Shari announced a RM500 million state government housing initiative to deliver 8,000 affordable units in Shah Alam, Klang, and Sepang by end of 2027, priced between RM150,000–RM280,000 exclusively for Selangor residents earning below RM7,000 monthly. Applications will open through the Rumah Selangorku portal in July 2025.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/nation/2026/05/15/selangor-affordable-housing-rm500m-8000-units",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-15T11:00:00+08:00",
  },
  {
    externalId: "demo_024",
    title: "Education Ministry Proposes Revised University Entry Requirements, Removing MUET Mandatory Band",
    summary:
      "The Ministry of Education is consulting on a proposal to remove the mandatory MUET Band 3 requirement for public university entry, replacing it with a broader English proficiency assessment and co-curricular score system starting for the 2026 intake. The change aims to reduce barriers for students from rural areas while maintaining academic standards.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/news/education/2026/05/15/education-ministry-university-entry-muet-changes",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-15T13:00:00+08:00",
  },
  {
    externalId: "demo_025",
    title: "Cabinet Reshuffle Imminent: Agriculture, Communications and Transport Ministries Tipped for Restructuring",
    summary:
      "Political sources indicate a Cabinet reshuffle is expected before Parliament's August break, with the Agriculture and Food Security, Communications, and Transport ministries potentially merged or restructured to reduce duplication and cut administrative costs by an estimated RM800 million annually. Coalition partners PKR, DAP, and Amanah are in active negotiations over ministerial allocations.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/malaysia/2026/05/14/cabinet-reshuffle-three-ministries-restructuring-imminent",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-14T09:00:00+08:00",
  },
  {
    externalId: "demo_026",
    title: "Malaysia-China Bilateral Trade Agreement Enters Final Negotiation Round in Beijing",
    summary:
      "Malaysian and Chinese trade negotiators concluded the penultimate round of talks on an Enhanced Free Trade Agreement in Beijing, with tariff reductions on palm oil, rubber products, and electrical components among the final sticking points. Officials expect a signing ceremony at the ASEAN Summit in October 2025 pending resolution of the digital trade chapter.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2436700",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-14T11:30:00+08:00",
  },
  {
    externalId: "demo_027",
    title: "Local Council Elections Bill Tabled for First Reading — Earliest Vote in 2026 if Passed",
    summary:
      "The Local Government and Urban Wellbeing Ministry tabled the Local Government Elections Bill 2025 for its first reading in Parliament, proposing to restore local council elections suspended since 1965 for urban areas with populations above 300,000. If the bill passes its third reading, the first local elections could be held in major cities by mid-2026.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/nation/2026/05/13/local-council-elections-bill-tabled-parliament",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-13T14:00:00+08:00",
  },
  {
    externalId: "demo_028",
    title: "Penang Tunnel Project Faces Fresh Delay — Completion Pushed to 2028 Over Geological Issues",
    summary:
      "The RM6.3 billion Penang undersea tunnel project faces a new 18-month delay after surveyors discovered unexpected soft soil deposits requiring an additional piling depth of 35 metres across a 2.4 km stretch under the Penang Strait. The contractor consortium, Gamuda-Ketua, submitted a revised completion date of Q2 2028 compared to the originally planned Q4 2026 target.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/news/nation/2026/05/13/penang-tunnel-delay-geological-soil-2028",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-13T16:00:00+08:00",
  },
  {
    externalId: "demo_029",
    title: "Health Ministry Announces Free Cancer Screening for All Malaysians Above 40 from June 2025",
    summary:
      "Health Minister Datuk Seri Dzulkefly Ahmad announced that free cancer screening covering colorectal, breast, and cervical cancers will be available at all 1,000-plus Klinik Kesihatan nationwide for citizens above 40 from 1 June 2025. The programme, funded by a RM380 million federal allocation, targets early detection with a goal of screening 2 million Malaysians in year one.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/malaysia/2026/05/12/free-cancer-screening-over-40-klinik-kesihatan-june",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-12T10:00:00+08:00",
  },
  {
    externalId: "demo_030",
    title: "MACC Investigating RM120 Million Procurement Irregularity in Defence Ministry Equipment Deals",
    summary:
      "The Malaysian Anti-Corruption Commission confirmed it is investigating a RM120 million procurement irregularity involving three defence equipment contracts awarded between 2020 and 2022, with ten individuals including a former senior official under investigation. MACC Chief Commissioner Tan Sri Azam Baki said initial findings indicate inflated pricing of up to 340% above market value for specific logistics equipment.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/nation/2026/05/12/macc-rm120m-defence-procurement-investigation",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-12T14:30:00+08:00",
  },
  {
    externalId: "demo_031",
    title: "Malaysia Formally Joins BRICS Partnership Framework, Enhancing Trade with Key Emerging Markets",
    summary:
      "Malaysia officially joined BRICS as a partner state at the Johannesburg summit, granting Malaysian exporters preferential access to a combined USD 29 trillion market spanning Brazil, Russia, India, China, and South Africa. The partnership does not require full political alignment with BRICS positions and was supported unanimously by Cabinet as a strategic diversification of trade partnerships.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2436820",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-11T08:30:00+08:00",
  },
  {
    externalId: "demo_032",
    title: "New MyKad Digital ID Pilot Launches in KL — Full Rollout to Replace Physical Card by 2027",
    summary:
      "The National Registration Department launched a digital identity pilot programme in Kuala Lumpur covering 50,000 residents, enabling citizens to store their MyKad credentials on the MyID mobile app for use at government counters, hospital check-ins, and airport immigration. The full nationwide digital ID rollout is planned for 2027, with physical MyKad remaining valid during the transition period.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/news/nation/2026/05/11/digital-mykad-pilot-kl-myid-app-2027",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-11T10:00:00+08:00",
  },
  {
    externalId: "demo_033",
    title: "Government Freezes Non-Critical Civil Service Hiring — 14,000 Vacancies Put on Hold",
    summary:
      "The Public Service Department announced an immediate freeze on filling 14,000 non-critical civil service vacancies across ministries and departments as part of fiscal consolidation measures, expected to save RM1.8 billion annually in salary expenditure. Essential services including healthcare, education, and police are exempt from the freeze.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/malaysia/2026/05/10/civil-service-hiring-freeze-14000-vacancies-hold",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-10T09:30:00+08:00",
  },
  {
    externalId: "demo_034",
    title: "Malaysia Pushes Back on EU Deforestation Regulation — Requests Two-Year Implementation Delay",
    summary:
      "Malaysia's Ministry of Plantation Industries formally requested the European Commission extend the EU Deforestation Regulation compliance deadline by two years from December 2025 to December 2027, citing insufficient time for small palm oil farmers to complete land certification requirements. The regulation requires proof that commodities do not come from recently deforested land, affecting RM8.2 billion in annual palm oil exports to Europe.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/nation/2026/05/10/malaysia-eu-deforestation-regulation-delay-request",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-10T11:00:00+08:00",
  },
  {
    externalId: "demo_035",
    title: "PM Anwar Meets IMF Chief in Washington — Discusses Fiscal Consolidation and Subsidy Reform Path",
    summary:
      "Prime Minister Datuk Seri Anwar Ibrahim met IMF Managing Director Kristalina Georgieva on the sidelines of the G20 Finance Ministers' meeting to discuss Malaysia's medium-term fiscal consolidation strategy, including the timeline for completing fuel subsidy rationalisation and achieving a budget deficit below 3% of GDP by 2027. The IMF praised Malaysia's economic management while urging faster subsidy reform implementation.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2436950",
    topic: "Malaysian Politics",
    publishedAt: "2026-05-10T14:00:00+08:00",
  },

  // ─── TECH & AI (15 articles) ──────────────────────────────────────────────────
  {
    externalId: "demo_036",
    title: "Malaysia Launches National AI Governance Framework — Companies Must Register AI Systems by 2026",
    summary:
      "The Ministry of Digital announced Malaysia's National AI Governance Framework requiring businesses deploying AI systems that affect consumer decisions — including loan approvals, hiring, and content moderation — to register with a new AI Registry by January 2026 and comply with fairness and transparency audit requirements. High-risk AI applications in healthcare and financial services face mandatory third-party assessments.",
    sourceName: "Tech in Asia",
    sourceUrl: "https://www.techinasia.com",
    articleUrl: "https://www.techinasia.com/malaysia-national-ai-governance-framework-2026-registry",
    topic: "Tech & AI",
    publishedAt: "2026-05-16T13:00:00+08:00",
  },
  {
    externalId: "demo_037",
    title: "Google Opens Second Cloud Region in Malaysia, Creating 2,000 Direct Jobs in KL Sentral",
    summary:
      "Google Cloud inaugurated its second Malaysian cloud region in KL Sentral, adding 32 data centre zones and committing USD 1.2 billion in total investment, which the government estimates will create 2,000 direct technology jobs and support 10,000 indirect positions over five years. The new region reduces data latency for Southeast Asian customers from 80ms to under 5ms for Malaysia-based workloads.",
    sourceName: "Tech in Asia",
    sourceUrl: "https://www.techinasia.com",
    articleUrl: "https://www.techinasia.com/google-cloud-second-region-malaysia-kl-sentral-2000-jobs",
    topic: "Tech & AI",
    publishedAt: "2026-05-16T10:30:00+08:00",
  },
  {
    externalId: "demo_038",
    title: "TikTok Commits RM1.5 Billion to Malaysia Data Centre in Cyberjaya — Largest Tech FDI of 2025",
    summary:
      "ByteDance confirmed a RM1.5 billion data centre investment in Cyberjaya to support TikTok's Southeast Asian operations, representing the largest single technology FDI commitment in Malaysia in 2025. The 28-acre facility will be powered by 100% renewable energy from Sarawak hydropower and is expected to be operational by Q3 2026, creating 800 local engineering positions.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/tech/2026/05/15/tiktok-rm15b-data-centre-cyberjaya-largest-tech-fdi-2025",
    topic: "Tech & AI",
    publishedAt: "2026-05-15T09:00:00+08:00",
  },
  {
    externalId: "demo_039",
    title: "Grab Launches GrabAI Assistant in Malaysia — Automates Driver Earnings Optimisation",
    summary:
      "Grab Malaysia launched GrabAI, an in-app AI assistant for drivers and delivery partners that analyses real-time demand patterns to recommend optimal working hours, zones, and surge timing, with early beta users reporting an average 18% increase in hourly earnings. The feature uses local Malaysian traffic and demand data and is available to all GrabCar, GrabFood, and GrabExpress partners from 1 June.",
    sourceName: "Tech in Asia",
    sourceUrl: "https://www.techinasia.com",
    articleUrl: "https://www.techinasia.com/grab-ai-assistant-malaysia-driver-earnings-optimisation",
    topic: "Tech & AI",
    publishedAt: "2026-05-15T11:30:00+08:00",
  },
  {
    externalId: "demo_040",
    title: "Aerodyne Raises USD 30 Million Series C to Expand Drone-as-a-Service Across 20 New Markets",
    summary:
      "Malaysian drone technology company Aerodyne secured USD 30 million in Series C funding led by Kenanga Investment Bank and Saudi Aramco Ventures, valuing the Subang Jaya-based firm at approximately USD 350 million. The funds will fuel expansion into 20 new markets including the Middle East, Europe, and East Africa for infrastructure inspection, precision agriculture, and emergency response services.",
    sourceName: "Tech in Asia",
    sourceUrl: "https://www.techinasia.com",
    articleUrl: "https://www.techinasia.com/aerodyne-usd30m-series-c-drone-as-a-service-20-markets",
    topic: "Tech & AI",
    publishedAt: "2026-05-14T09:30:00+08:00",
  },
  {
    externalId: "demo_041",
    title: "Cybersecurity Act Amendments: Malaysian Companies Face Up to RM500,000 Fine Per Data Breach",
    summary:
      "The amended Cybersecurity Act 2025 raises maximum penalties for organisations failing to report data breaches to CyberSecurity Malaysia within 72 hours to RM500,000 per incident, plus RM50,000 per day for continuing violations. Companies handling personal data of more than 10,000 Malaysian customers must also appoint a certified Data Protection Officer by January 2026.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/tech/tech-news/2026/05/14/cybersecurity-act-amendments-rm500k-fine-data-breach",
    topic: "Tech & AI",
    publishedAt: "2026-05-14T13:00:00+08:00",
  },
  {
    externalId: "demo_042",
    title: "5G Coverage Reaches 80% of Populated Areas — MCMC Annual Digital Report 2025",
    summary:
      "Malaysia achieved 5G network coverage across 80.3% of populated areas by end of Q1 2025, up from 67% a year earlier, with Digital Nasional Berhad confirming all 16 states now have active 5G infrastructure. Average 5G download speeds in urban areas hit 412 Mbps, though rural areas average 89 Mbps and coverage in Sabah and Sarawak lags at 54% of populated zones.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2437050",
    topic: "Tech & AI",
    publishedAt: "2026-05-13T08:00:00+08:00",
  },
  {
    externalId: "demo_043",
    title: "Malaysian Banks Roll Out AI-Powered Fraud Detection Blocking RM200 Million Monthly in Scams",
    summary:
      "A consortium of eight Malaysian banks including Maybank, CIMB, and Public Bank completed a joint AI fraud detection system deployment that detected and blocked RM200 million per month in suspicious transactions during a six-month trial period. The system uses behavioural biometrics and network graph analysis to flag mule account transfers, with a false positive rate of under 0.3%.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/banks-ai-fraud-detection-rm200m-blocked-monthly",
    topic: "Tech & AI",
    publishedAt: "2026-05-13T10:00:00+08:00",
  },
  {
    externalId: "demo_044",
    title: "Apple Vision Pro Now Available in Malaysia from RM16,999 — Limited Stocks at KLCC and Mid Valley",
    summary:
      "Apple officially launched Vision Pro in Malaysia at a starting price of RM16,999 for the 256GB model, available at Apple Stores in KLCC and Mid Valley Megamall and through authorised resellers. Pre-order waitlists filled within four hours of opening, with Maxis and Celcom offering 24-month instalment plans from RM708/month with 5G data bundle packages.",
    sourceName: "Tech in Asia",
    sourceUrl: "https://www.techinasia.com",
    articleUrl: "https://www.techinasia.com/apple-vision-pro-malaysia-rm16999-klcc-mid-valley",
    topic: "Tech & AI",
    publishedAt: "2026-05-12T09:00:00+08:00",
  },
  {
    externalId: "demo_045",
    title: "Putrajaya Launches MyGovAI Chatbot — Handles 80 Government Service Queries Instantly",
    summary:
      "The Ministry of Digital launched MyGovAI, a Bahasa Malaysia and English AI chatbot on the MyGov portal that handles over 80 government service enquiries including MyKad applications, SSM registration, PTPTN repayment, and income tax filing guidance. In its first week, MyGovAI handled 340,000 queries with a 94% resolution rate, compared to the previous call centre average of 2,200 calls daily.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2437120",
    topic: "Tech & AI",
    publishedAt: "2026-05-12T14:00:00+08:00",
  },
  {
    externalId: "demo_046",
    title: "Malaysia Aims to Train 50,000 AI Specialists by 2026 — HRDF Funds 200 Certified Courses",
    summary:
      "The Ministry of Human Resources announced 50,000 AI and machine learning specialists will be trained by 2026 under the Madani Economy Digital Skills initiative, with HRDF approving 200 AI certification courses from providers including AWS, Google, and local universities eligible for employer levy claims. Unemployed graduates can access the courses at zero cost through the JTM Digital Reskilling Programme.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/business/2026/05/11/malaysia-50000-ai-specialists-2026-hrdf-200-courses",
    topic: "Tech & AI",
    publishedAt: "2026-05-11T09:00:00+08:00",
  },
  {
    externalId: "demo_047",
    title: "Penang Semiconductor Industry Adds 3,500 Jobs in Q1 as Intel and Infineon Expand Capacity",
    summary:
      "Penang's semiconductor sector created 3,500 new jobs in Q1 2025 as Intel Malaysia's Batu Kawan campus completed a USD 700 million fabrication line expansion and Infineon Technologies broke ground on a new chip testing facility in Kulim Hi-Tech Park. InvestPenang confirmed total capital expenditure commitments for 2025 now exceed RM8 billion.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/business/business-news/2026/05/11/penang-semiconductor-3500-jobs-q1-intel-infineon",
    topic: "Tech & AI",
    publishedAt: "2026-05-11T11:30:00+08:00",
  },
  {
    externalId: "demo_048",
    title: "ByteDance Acquires Malaysian Fintech Startup Jirnexu for USD 45 Million",
    summary:
      "ByteDance completed its acquisition of Petaling Jaya-based fintech startup Jirnexu, operator of RinggitPlus financial comparison platform, for USD 45 million, signalling the Chinese tech giant's intent to enter Malaysia's digital financial services market. The acquisition gives ByteDance access to RinggitPlus' 4.2 million registered users and partnerships with over 60 Malaysian banks and insurers.",
    sourceName: "Tech in Asia",
    sourceUrl: "https://www.techinasia.com",
    articleUrl: "https://www.techinasia.com/bytedance-acquires-jirnexu-ringgitplus-usd45m-malaysia",
    topic: "Tech & AI",
    publishedAt: "2026-05-10T09:00:00+08:00",
  },
  {
    externalId: "demo_049",
    title: "BFM89.9: Is Malaysia Ready for the AI Economy? | Full Episode",
    summary:
      "BFM89.9 Business Radio hosts a panel discussion with AI industry leaders, education experts, and policy makers on whether Malaysia's workforce, regulatory environment, and infrastructure are ready for the AI-driven economy. Topics covered include the 50,000 AI specialist target, data centre growth, and what specific skills Malaysian workers need to remain relevant by 2027.",
    sourceName: "BFM89.9",
    sourceUrl: "https://www.youtube.com/c/BFM89",
    articleUrl: "https://www.youtube.com/watch?v=bfm_ai_economy_2025",
    topic: "Tech & AI",
    publishedAt: "2026-05-10T10:00:00+08:00",
    isVideo: true,
  },
  {
    externalId: "demo_050",
    title: "KiniTV: Inside Malaysia's Data Centre Boom — Who Benefits and at What Cost?",
    summary:
      "KiniTV investigates Malaysia's data centre construction surge worth over RM20 billion in approved investments, examining the economic benefits of job creation and FDI against concerns including water consumption of up to 1.5 million litres daily per facility, rising electricity demand, and land use changes in Johor and Selangor. Features interviews with data centre operators, local residents, and environmental NGOs.",
    sourceName: "KiniTV",
    sourceUrl: "https://www.youtube.com/c/KiniTV",
    articleUrl: "https://www.youtube.com/watch?v=kinitv_datacenter_boom_2025",
    topic: "Tech & AI",
    publishedAt: "2026-05-10T12:00:00+08:00",
    isVideo: true,
  },

  // ─── HEALTH (12 articles) ─────────────────────────────────────────────────────
  {
    externalId: "demo_051",
    title: "Free Cancer Screening: How to Register, What's Covered, and Which Clinics Participate",
    summary:
      "Malaysia's free cancer screening programme covering colorectal, breast, and cervical cancers opens registration at myCancerScreening.moh.gov.my from 1 June 2025 for all citizens above 40 — no referral or appointment needed, walk-in to any of 1,032 participating Klinik Kesihatan. Screening includes colonoscopy referral, mammogram for women above 40, and HPV DNA test for cervical cancer detection.",
    sourceName: "CodeBlue",
    sourceUrl: "https://codeblue.galencentre.org",
    articleUrl: "https://codeblue.galencentre.org/2026/05/16/free-cancer-screening-how-register-clinics",
    topic: "Health",
    publishedAt: "2026-05-16T07:30:00+08:00",
  },
  {
    externalId: "demo_052",
    title: "Dengue Cases Spike 40% in Selangor — Health Ministry Issues Yellow Alert for 12 Districts",
    summary:
      "Selangor recorded 4,821 dengue cases in the first two weeks of May 2025, a 40% increase from the same period last year, prompting the Health Ministry to issue Yellow Alert status for 12 hotspot districts including Petaling, Hulu Langat, and Klang. Residents in these areas are urged to check for stagnant water every three days and seek treatment if fever persists beyond 48 hours.",
    sourceName: "CodeBlue",
    sourceUrl: "https://codeblue.galencentre.org",
    articleUrl: "https://codeblue.galencentre.org/2026/05/15/dengue-spike-40pct-selangor-yellow-alert",
    topic: "Health",
    publishedAt: "2026-05-15T08:30:00+08:00",
  },
  {
    externalId: "demo_053",
    title: "HPV Vaccine Now Free for All Girls and Boys Under 18 — Expansion Announced by Health Ministry",
    summary:
      "Health Minister Datuk Seri Dzulkefly Ahmad announced the government-funded HPV vaccination programme will expand to include all Malaysian boys under 18, in addition to the existing programme for girls, from August 2025. The gender-neutral expansion, costing RM180 million annually, aims to achieve herd immunity for HPV-related cancers and is aligned with WHO recommendations.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/life/2026/05/14/hpv-vaccine-free-boys-girls-under-18-malaysia",
    topic: "Health",
    publishedAt: "2026-05-14T09:00:00+08:00",
  },
  {
    externalId: "demo_054",
    title: "Mental Health Leave Now Recognised Under Employment Act Amendments — Up to 3 Days Per Year",
    summary:
      "Amendments to the Employment Act 1955 now explicitly recognise certified mental health leave as separate from sick leave, allowing employees with documented mental health conditions up to 3 additional days per year covered by employer-funded leave entitlement. The amendment, tabled by the Human Resources Ministry, takes effect 1 July 2025 and applies to all employees regardless of salary or sector.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/news/nation/2026/05/13/mental-health-leave-employment-act-3-days",
    topic: "Health",
    publishedAt: "2026-05-13T10:00:00+08:00",
  },
  {
    externalId: "demo_055",
    title: "Hospital Kuala Lumpur New Wing Opens — 500 Additional Beds, Cuts Specialist Wait Time by 40%",
    summary:
      "A new eight-floor wing at Hospital Kuala Lumpur officially opened, adding 500 inpatient beds, four new operating theatres, and specialist clinics for oncology, cardiology, and neurology. HKL expects the expansion to reduce average specialist outpatient waiting times from 82 days to under 50 days by end of 2025, benefiting approximately 320,000 patients annually.",
    sourceName: "CodeBlue",
    sourceUrl: "https://codeblue.galencentre.org",
    articleUrl: "https://codeblue.galencentre.org/2026/05/12/hospital-kuala-lumpur-new-wing-500-beds-open",
    topic: "Health",
    publishedAt: "2026-05-12T09:30:00+08:00",
  },
  {
    externalId: "demo_056",
    title: "Sugar Tax Expanded: Packaged Fruit Juices Above 12g Sugar per 100ml Taxed from July",
    summary:
      "The Customs Department confirmed the sugar-sweetened beverage excise duty expansion to include pre-packaged 100% fruit juices containing more than 12 grams of sugar per 100ml, effective 1 July 2025 at RM0.40 per litre. Popular products like Tropicana 100% Orange Juice and Marigold Pineapple Juice will see retail price increases of approximately RM0.60–RM1.20 per carton.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/life/2026/05/11/sugar-tax-expanded-packaged-juices-12g-july-2025",
    topic: "Health",
    publishedAt: "2026-05-11T08:00:00+08:00",
  },
  {
    externalId: "demo_057",
    title: "Flavoured E-Cigarettes Banned in Malaysia — Vape Regulations Tightened from 1 August",
    summary:
      "The Health Ministry issued new vaping regulations under the Control of Tobacco Product and Smoking Act 2023 banning the sale of all flavoured e-cigarette liquids from 1 August 2025, leaving only plain tobacco-flavour vape products legal. Retailers holding existing flavoured stock must dispose of it by 31 July or face fines up to RM10,000 per offence, while online sales platforms will be required to verify buyer ages.",
    sourceName: "CodeBlue",
    sourceUrl: "https://codeblue.galencentre.org",
    articleUrl: "https://codeblue.galencentre.org/2026/05/10/flavoured-e-cigarettes-banned-vape-regulations-august",
    topic: "Health",
    publishedAt: "2026-05-10T08:00:00+08:00",
  },
  {
    externalId: "demo_058",
    title: "Health Ministry Warns of Counterfeit Slimming Supplements Containing Undeclared Sibutramine",
    summary:
      "The Ministry of Health issued an urgent public health alert warning against 14 slimming supplement products circulating on TikTok Shop, Shopee, and Lazada that were found to contain undeclared sibutramine, a banned drug linked to heart attacks and strokes. The products, many marketed as 'natural herbal' supplements priced RM30–RM120, have been referred to KPDNHEP for immediate enforcement action.",
    sourceName: "CodeBlue",
    sourceUrl: "https://codeblue.galencentre.org",
    articleUrl: "https://codeblue.galencentre.org/2026/05/10/counterfeit-slimming-supplements-sibutramine-warning",
    topic: "Health",
    publishedAt: "2026-05-10T11:00:00+08:00",
  },
  {
    externalId: "demo_059",
    title: "Malaysia Obesity Rate Hits 54.4% — Government Launches Healthy Malaysia 2030 Campaign",
    summary:
      "The National Health and Morbidity Survey 2025 revealed 54.4% of Malaysian adults are either overweight or obese, with the rate among children aged 5–17 rising to 32.6%, prompting the Health Ministry to launch the Healthy Malaysia 2030 campaign targeting a reduction to 45% adult obesity by the decade's end. The initiative includes free nutritional counselling at Klinik Kesihatan and mandatory physical activity programmes in all public schools.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/news/nation/2026/05/10/malaysia-obesity-544pct-healthy-malaysia-2030",
    topic: "Health",
    publishedAt: "2026-05-10T12:00:00+08:00",
  },
  {
    externalId: "demo_060",
    title: "Traditional Medicine Practitioners to be Regulated Under New MOH Framework from 2026",
    summary:
      "The Health Ministry gazetted the Traditional and Complementary Medicine (T&CM) Practice Regulatory Framework requiring all TCM, Malay traditional medicine, and Ayurvedic practitioners to be licensed by the Malaysian Traditional and Complementary Medicine Board by 1 January 2026. Unlicensed practitioners face fines up to RM50,000 and up to two years imprisonment under the framework.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/life/2026/05/10/traditional-medicine-regulated-moh-framework-2026",
    topic: "Health",
    publishedAt: "2026-05-10T14:00:00+08:00",
  },
  {
    externalId: "demo_061",
    title: "Free HIV Testing Expanded to All 1,032 Klinik Kesihatan Nationwide — Walk-In Available",
    summary:
      "The Health Ministry expanded free, confidential HIV testing to all 1,032 Klinik Kesihatan nationwide, making Malaysia the first country in Southeast Asia to offer universal HIV testing access through public primary care without appointment. The programme, part of the 90-90-90 national HIV elimination strategy, also provides same-day PrEP prescriptions for high-risk individuals.",
    sourceName: "CodeBlue",
    sourceUrl: "https://codeblue.galencentre.org",
    articleUrl: "https://codeblue.galencentre.org/2026/05/10/free-hiv-testing-all-klinik-kesihatan-nationwide",
    topic: "Health",
    publishedAt: "2026-05-10T15:00:00+08:00",
  },
  {
    externalId: "demo_062",
    title: "KKM Malaysia: What the New Mental Health Policy Means for You | Official Explainer",
    summary:
      "The Ministry of Health's official YouTube channel releases a detailed explainer on the Malaysia Mental Health Policy 2025 covering entitlements under the Employment Act mental health leave amendment, how to access free counselling at Klinik Kesihatan, and what changes are coming to psychiatric bed capacity under the Public Health Sector Transformation Plan. Features interviews with psychiatrists and patient advocates.",
    sourceName: "KKM Malaysia",
    sourceUrl: "https://www.youtube.com/@KKMalaysia",
    articleUrl: "https://www.youtube.com/watch?v=kkm_mental_health_policy_2025",
    topic: "Health",
    publishedAt: "2026-05-10T16:00:00+08:00",
    isVideo: true,
  },

  // ─── PROPERTY (10 articles) ───────────────────────────────────────────────────
  {
    externalId: "demo_063",
    title: "KL Residential Property Prices Up 3.8% Year-on-Year — NAPIC Q1 2025 Report",
    summary:
      "Kuala Lumpur residential property prices rose 3.8% year-on-year in Q1 2025 based on National Property Information Centre data, with Bangsar South recording the sharpest gain at 6.2% and Mont Kiara condominiums up 4.9%. Transaction volumes increased 12% quarter-on-quarter, signalling renewed buyer confidence despite tight mortgage approval rates of 68%.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/kl-residential-property-up-38pct-napic-q1-2025",
    topic: "Property",
    publishedAt: "2026-05-16T08:00:00+08:00",
  },
  {
    externalId: "demo_064",
    title: "HOC 2.0 Likely for H2 2025 — Developers on Standby for Stamp Duty and Interest Rate Incentives",
    summary:
      "Industry sources indicate the government is finalising a Homeownership Campaign 2.0 to launch in Q3 2025 offering full stamp duty exemption on properties below RM500,000 and a subsidised interest rate of 3.5% for first-time buyers. The Real Estate and Housing Developers' Association confirmed members have been briefed to prepare launch-ready stock for the incentive window.",
    sourceName: "EdgeProp",
    sourceUrl: "https://www.edgeprop.my",
    articleUrl: "https://www.edgeprop.my/content/hoc-2-h2-2025-stamp-duty-interest-incentives",
    topic: "Property",
    publishedAt: "2026-05-15T10:00:00+08:00",
  },
  {
    externalId: "demo_065",
    title: "New MRT3 Stations Confirmed in PJ and Shah Alam — Property Values Along Route Tipped to Rise 15%",
    summary:
      "MRT Corp released the final alignment for the MRT3 Circle Line with 40 confirmed stations, including six new stops in Petaling Jaya and four in Shah Alam covering Subang Jaya, USJ, and Glenmarie. Property analysts at CBRE|WTW forecast 12–18% price appreciation for residential units within 800 metres of the new stations over the construction period to 2028.",
    sourceName: "EdgeProp",
    sourceUrl: "https://www.edgeprop.my",
    articleUrl: "https://www.edgeprop.my/content/mrt3-stations-pj-shah-alam-property-values-appreciation",
    topic: "Property",
    publishedAt: "2026-05-14T11:00:00+08:00",
  },
  {
    externalId: "demo_066",
    title: "Johor-Singapore SEZ Attracts RM12 Billion in Committed Investment — 18 Data Centres Approved",
    summary:
      "The Johor-Singapore Special Economic Zone attracted RM12 billion in committed investment within 60 days of official establishment, including 18 approved data centre projects across Iskandar Malaysia and Pengerang Industrial Corridor. Johor's Chief Minister confirmed land prices in Nusajaya and Medini have increased 22% since the SEZ announcement, with residential property also seeing above-average demand.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/johor-singapore-sez-rm12b-investment-18-data-centres",
    topic: "Property",
    publishedAt: "2026-05-13T09:00:00+08:00",
  },
  {
    externalId: "demo_067",
    title: "KL Rental Market Hits 10-Year High — Montly Rent for 3-Bedroom Condo Averages RM3,400",
    summary:
      "Monthly rental rates for three-bedroom condominiums in central Kuala Lumpur reached an average of RM3,400 in Q1 2025, the highest in a decade, driven by returning expatriates, reduced affordable housing supply, and increased preference for renting among younger Malaysians. Areas like KLCC, Bangsar, and Damansara Heights saw 18–22% rent increases year-on-year.",
    sourceName: "EdgeProp",
    sourceUrl: "https://www.edgeprop.my",
    articleUrl: "https://www.edgeprop.my/content/kl-rental-market-10-year-high-3400-monthly-condo",
    topic: "Property",
    publishedAt: "2026-05-12T10:00:00+08:00",
  },
  {
    externalId: "demo_068",
    title: "First-Time Homebuyer Scheme Expanded — Income Ceiling Raised to RM10,000 Monthly",
    summary:
      "The National Housing Department announced the My First Home Scheme income eligibility ceiling has been raised from RM7,000 to RM10,000 monthly household income, opening the zero-deposit, government-guaranteed mortgage programme to an additional 180,000 potential first-time buyers. Eligible properties extend up to RM500,000 in the Klang Valley and RM400,000 in East Malaysia.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2437250",
    topic: "Property",
    publishedAt: "2026-05-12T12:00:00+08:00",
  },
  {
    externalId: "demo_069",
    title: "Government Takes Over 12 Abandoned Housing Projects — 8,400 Affected Buyers to Get Completed Units",
    summary:
      "The Ministry of Housing and Local Government assumed control of 12 abandoned housing developments affecting 8,400 buyers across Selangor, Perak, and Johor, appointing Pengurusan Aset Air to complete construction using a RM1.1 billion Special Fund for Abandoned Projects. Affected buyers will receive their completed units with no additional payments, and the contractors involved face debarment from future public housing projects.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/money/2026/05/10/12-abandoned-housing-projects-government-takeover-8400-buyers",
    topic: "Property",
    publishedAt: "2026-05-10T09:00:00+08:00",
  },
  {
    externalId: "demo_070",
    title: "Sabah Records 45% Surge in Property Enquiries from Peninsular Buyers — KK Leads Demand",
    summary:
      "Property enquiries in Sabah from Peninsular Malaysia buyers surged 45% in Q1 2025 compared to a year earlier, driven by Kota Kinabalu's growing appeal as a lifestyle destination and average property prices 38% below Kuala Lumpur levels. Kota Kinabalu City Park condominiums and Likas Bay landed properties topped the most-searched listings on PropertyGuru and iProperty.",
    sourceName: "EdgeProp",
    sourceUrl: "https://www.edgeprop.my",
    articleUrl: "https://www.edgeprop.my/content/sabah-property-enquiries-surge-45pct-peninsula-buyers-kk",
    topic: "Property",
    publishedAt: "2026-05-10T11:00:00+08:00",
  },
  {
    externalId: "demo_071",
    title: "EdgeProp: Petaling Jaya SS2 Sees Strongest Rental Demand in Selangor — Why Agents Are Bullish",
    summary:
      "EdgeProp's Q1 2025 rental market analysis identifies Petaling Jaya SS2 as Selangor's tightest rental market with average vacancy rates of just 2.1% and typical 3-bedroom terrace house rents reaching RM2,800–RM3,200 per month. The area's proximity to PJ State LRT station, completed MRT connectivity, and established school belt are cited as the primary demand drivers.",
    sourceName: "EdgeProp",
    sourceUrl: "https://www.edgeprop.my",
    articleUrl: "https://www.edgeprop.my/content/petaling-jaya-ss2-strongest-rental-selangor-q1-2025",
    topic: "Property",
    publishedAt: "2026-05-10T13:00:00+08:00",
  },
  {
    externalId: "demo_072",
    title: "PropertyGuru: Should You Buy or Rent in KL in 2025? | Full Market Analysis",
    summary:
      "PropertyGuru Malaysia's latest market analysis video compares the buy-vs-rent decision in Kuala Lumpur using actual Q1 2025 data: median purchase price RM620,000 for a 3-bedroom condo vs median rent RM2,800/month, working through mortgage affordability, opportunity cost of down payment, and the price-to-rent ratio of 18.4x that suggests buying is marginally favourable for those with stable 10-year horizons.",
    sourceName: "PropertyGuru MY",
    sourceUrl: "https://www.youtube.com/@PropertyGuruMalaysia",
    articleUrl: "https://www.youtube.com/watch?v=propertyguru_buy_rent_kl_2025",
    topic: "Property",
    publishedAt: "2026-05-10T14:00:00+08:00",
    isVideo: true,
  },

  // ─── FUEL & TRANSPORT (10 articles) ──────────────────────────────────────────
  {
    externalId: "demo_073",
    title: "RON95 Targeted Subsidy Registration Opens — Check Eligibility via MyKad Scan at Any Petronas",
    summary:
      "The Domestic Trade Ministry launched the RON95 Targeted Subsidy registration system, allowing vehicle owners to register at Petronas, Shell, and BHPetrol stations using MyKad scan or online at mysubs.gov.my to verify household income eligibility. Registered eligible vehicles will continue paying RM2.05 per litre; ineligible vehicles will pay market-rate prices from the implementation date in August 2025.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2437350",
    topic: "Fuel & Transport",
    publishedAt: "2026-05-16T07:00:00+08:00",
  },
  {
    externalId: "demo_074",
    title: "Electric Bus Fleet Expands to Penang and Johor Bahru — 60 New Rapid Buses on Key Routes",
    summary:
      "Prasarana Malaysia deployed 60 BYD electric buses on high-frequency routes in Penang Island and Johor Bahru as part of the Green Public Transport Initiative, replacing diesel buses that produce 11 times more emissions per passenger kilometre. The RM180 million fleet operates on Route 101 (Georgetown-Batu Feringgi) and Route 12 (JB City-Iskandar Puteri) with charging infrastructure powered by TNB's renewable tariff.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/malaysia/2026/05/15/electric-bus-fleet-penang-johor-bahru-rapid-byd",
    topic: "Fuel & Transport",
    publishedAt: "2026-05-15T09:00:00+08:00",
  },
  {
    externalId: "demo_075",
    title: "Highway Toll Restructuring Study Completed — Flat Rate of RM2 for Urban Expressways Proposed",
    summary:
      "A comprehensive highway toll restructuring study submitted to the Transport Ministry proposes replacing variable distance-based tolls on SPRINT, LDP, and NPE expressways with a flat RM2 entry fee for all vehicle classes, estimated to save regular commuters an average of RM180 per month. The proposal requires government compensation payments of RM1.4 billion annually to highway concessionaires and is being reviewed before a Cabinet decision expected in Q3 2025.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/news/nation/2026/05/14/toll-restructuring-flat-rate-rm2-urban-expressways",
    topic: "Fuel & Transport",
    publishedAt: "2026-05-14T10:30:00+08:00",
  },
  {
    externalId: "demo_076",
    title: "Proton Sales Jump 22% in Q1 — EV Model e.MAS 7 Accounts for 18% of Total Volume",
    summary:
      "Proton recorded 42,500 total vehicle sales in Q1 2025, a 22% year-on-year increase, with the electric Proton e.MAS 7 SUV contributing 7,650 units at 18% of total volume since its January launch at a price of RM122,800. The X70 and Saga remain Proton's best sellers but the e.MAS 7 backlogs now stretch to September 2025 for the premium variant.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/business/2026/05/13/proton-sales-22pct-q1-emas7-ev",
    topic: "Fuel & Transport",
    publishedAt: "2026-05-13T08:30:00+08:00",
  },
  {
    externalId: "demo_077",
    title: "LRT3 Shah Alam Line on Track for August 2025 — Trial Runs Complete, 24 Stations Ready",
    summary:
      "Prasarana confirmed all 24 stations on the LRT3 Shah Alam line from Johan Setia to Bandar Utama have completed trial passenger runs with no major technical issues, keeping the August 2025 commercial operation target intact. The line will be integrated with KTM Komuter, Rapid KL bus, and feeder services, and the initial Phase 1 daily ridership target is 80,000 passengers.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2437400",
    topic: "Fuel & Transport",
    publishedAt: "2026-05-12T09:00:00+08:00",
  },
  {
    externalId: "demo_078",
    title: "Ride-Hailing Drivers Get Mandatory Insurance Coverage Under Updated Road Transport Act",
    summary:
      "Amendments to the Road Transport Act 1987 effective 1 July 2025 require all e-hailing platforms operating in Malaysia to provide minimum RM100,000 personal accident insurance and RM500,000 third-party liability coverage for drivers during active trips, at the platform's cost. Grab, AirAsia Ride, and InDriver are currently negotiating group insurance premiums estimated at RM80–RM120 per driver monthly.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/money/2026/05/12/ride-hailing-drivers-mandatory-insurance-road-transport-act",
    topic: "Fuel & Transport",
    publishedAt: "2026-05-12T11:30:00+08:00",
  },
  {
    externalId: "demo_079",
    title: "MyRapid Monthly Pass Price Frozen Until End 2025 — No Increase for Bus, LRT, and MRT",
    summary:
      "Prasarana Malaysia confirmed the MyRapid unlimited monthly travel pass will remain at RM100 for adults and RM50 for senior citizens and students until 31 December 2025, absorbing the fuel and operational cost increase in the current government subsidy framework. The freeze covers all Rapid KL bus, LRT Kelana Jaya, Ampang, and Putrajaya lines as well as MRT Kajang and Putrajaya lines.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2437480",
    topic: "Fuel & Transport",
    publishedAt: "2026-05-11T08:00:00+08:00",
  },
  {
    externalId: "demo_080",
    title: "Road Tax Restructured: Motorcycles Below 150cc to Pay Just RM2 Annually from July",
    summary:
      "The Road Transport Department will restructure motorcycle road tax from July 2025, reducing annual fees for motorcycles below 150cc to RM2, a drop from the current RM22–RM36 range, as part of the lower-income transport affordability package. Motorcycles above 500cc will see road tax increase by 8–15% to partially offset the revenue reduction from the smaller engine category.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/business/2026/05/11/road-tax-restructured-motorcycles-150cc-rm2",
    topic: "Fuel & Transport",
    publishedAt: "2026-05-11T10:30:00+08:00",
  },
  {
    externalId: "demo_081",
    title: "DBKL Launches Pothole Repair Blitz — 90% of KL Potholes to Be Fixed Within 30 Days",
    summary:
      "Dewan Bandaraya Kuala Lumpur launched a RM28 million Emergency Pothole Repair Programme deploying 24 specialised repair teams targeting over 4,200 identified potholes across 648km of KL roads within 30 days, with a performance bond requiring RM5,000 deduction per pothole exceeding the deadline. Residents can report new potholes via the Urus KL app with a 48-hour response SLA from May 2025.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/malaysia/2026/05/10/dbkl-pothole-repair-rm28m-4200-potholes-30-days",
    topic: "Fuel & Transport",
    publishedAt: "2026-05-10T08:00:00+08:00",
  },
  {
    externalId: "demo_082",
    title: "AutoWorld MY: Malaysia's 3,000 New EV Charging Stations — Where Are They and Are They Fast Enough?",
    summary:
      "AutoWorld Malaysia's YouTube channel reviews the government's 3,000 new EV charging station rollout plan, visiting 15 sites across the Klang Valley to test actual charging speeds vs advertised specs. Coverage includes DC fast chargers at major highway rest stops, AC chargers in shopping mall car parks, and the Charge&Drive app interface, with a comparison of charging costs per 100km across different providers.",
    sourceName: "AutoWorld MY",
    sourceUrl: "https://www.youtube.com/@AutoWorldMY",
    articleUrl: "https://www.youtube.com/watch?v=autoworld_ev_charging_3000_stations",
    topic: "Fuel & Transport",
    publishedAt: "2026-05-10T14:30:00+08:00",
    isVideo: true,
  },

  // ─── JOBS & CAREER (8 articles) ──────────────────────────────────────────────
  {
    externalId: "demo_083",
    title: "Malaysia Unemployment Rate Holds at 3.3% — 180,000 Graduates Still Seeking First Job",
    summary:
      "Malaysia's unemployment rate remained stable at 3.3% in March 2025 with 531,000 unemployed individuals according to DOSM, but the youth unemployment rate for those aged 15–24 reached 11.8% and an estimated 180,000 recent graduates remain jobless six months after completion. The graduate unemployment rate is highest in the arts and humanities fields at 24.1% versus engineering at 6.3%.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/business/2026/05/13/unemployment-3pct-180000-graduates-jobless",
    topic: "Jobs & Career",
    publishedAt: "2026-05-13T08:00:00+08:00",
  },
  {
    externalId: "demo_084",
    title: "Minimum Wage to Rise to RM1,700 from July 2025 — 1.6 Million Workers to Benefit",
    summary:
      "The Human Resources Ministry officially gazetted the new national minimum wage of RM1,700 per month effective 1 July 2025, up from RM1,500, with an estimated 1.6 million private sector workers across all states set to receive higher pay. SMEs employing five or fewer workers are granted a six-month grace period until 31 December 2025 to comply without penalty.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2437550",
    topic: "Jobs & Career",
    publishedAt: "2026-05-12T10:30:00+08:00",
  },
  {
    externalId: "demo_085",
    title: "Government Agencies Now Allowed 2 Work-From-Home Days Weekly — Circular Issued to All Ministries",
    summary:
      "The Public Service Department issued a circular allowing all federal government employees except frontline service personnel to work from home up to two days per week at departmental discretion, effective immediately following Cabinet approval. Agency heads must establish department-level WFH policies by end of June and ensure service delivery metrics are not impacted, with quarterly reviews by JPA.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/news/nation/2026/05/12/government-agencies-wfh-2-days-circular-ministries",
    topic: "Jobs & Career",
    publishedAt: "2026-05-12T12:00:00+08:00",
  },
  {
    externalId: "demo_086",
    title: "HRDF Releases Full List of 200 Claimable AI Upskilling Courses — Applications Open Now",
    summary:
      "The Human Resources Development Fund published a complete list of 200 AI and digital skills upskilling courses from certified training providers that employers can claim under the HRD Levy scheme, covering topics from Python programming and machine learning to AI ethics and generative AI tools. Employers must submit claims through the HRD Corp e-TiS system with a course completion certificate; per-employee claimable amount is capped at RM8,000.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/money/2026/05/11/hrdf-200-ai-upskilling-courses-claimable-applications",
    topic: "Jobs & Career",
    publishedAt: "2026-05-11T09:30:00+08:00",
  },
  {
    externalId: "demo_087",
    title: "Fresh Graduate Median Salary Rises to RM2,400 in 2024 — Tech and Engineering Highest at RM3,100",
    summary:
      "DOSM's Graduate Tracer Study 2024 shows the median monthly starting salary for Malaysian fresh graduates rose to RM2,400, up from RM2,100 in 2022, with information technology and engineering disciplines commanding the highest medians at RM3,100 and RM2,900 respectively. Social science graduates earn a median of RM1,900 while arts graduates have the lowest at RM1,750, still below the national minimum wage effective July 2025.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/business/2026/05/11/fresh-graduate-median-salary-rm2400-tech-engineering",
    topic: "Jobs & Career",
    publishedAt: "2026-05-11T11:00:00+08:00",
  },
  {
    externalId: "demo_088",
    title: "LinkedIn: Malaysia Ranks 4th in Southeast Asia for Tech Job Growth — 38,000 New Roles in Q1",
    summary:
      "LinkedIn's Q1 2025 Southeast Asia Employment Report places Malaysia fourth in the region for technology job growth with 38,000 new tech roles created, behind Indonesia, Vietnam, and Philippines but ahead of Thailand and Singapore in percentage growth terms. AI and machine learning roles grew 67% year-on-year while cybersecurity roles expanded 45%, driven by both local startups and multinational companies setting up regional tech hubs.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/malaysia-4th-sea-tech-job-growth-38000-roles-q1",
    topic: "Jobs & Career",
    publishedAt: "2026-05-10T09:30:00+08:00",
  },
  {
    externalId: "demo_089",
    title: "New SPM-Level Apprenticeship Programme in Manufacturing — RM1,200 Monthly Stipend for Trainees",
    summary:
      "The Ministry of Human Resources launched a structured 18-month apprenticeship programme for SPM school leavers in the electronics, automotive, and food processing manufacturing sectors, offering a RM1,200 monthly stipend during training with a guaranteed job placement at RM1,700 upon certification by accredited industry assessors. 5,000 positions are available for the July 2025 intake through the MyFuture Jobs portal.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2437620",
    topic: "Jobs & Career",
    publishedAt: "2026-05-10T11:30:00+08:00",
  },
  {
    externalId: "demo_090",
    title: "SOCSO Extends Coverage to Gig Workers — 2.1 Million Platform Riders and Delivery Partners Protected",
    summary:
      "The Social Security Organisation Malaysia announced mandatory SOCSO accident and illness coverage for 2.1 million gig economy workers including food delivery riders, ride-hailing drivers, and freelance platform workers effective 1 September 2025, with platforms required to contribute RM1.25 per active work-day per worker. Affected workers will receive up to RM4,000 monthly disability compensation and free access to Klinik Kesihatan for work-related injuries.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/business/2026/05/10/socso-gig-workers-coverage-21m-platform-riders",
    topic: "Jobs & Career",
    publishedAt: "2026-05-10T13:00:00+08:00",
  },

  // ─── FINANCE & INVESTING (5 articles) ────────────────────────────────────────
  {
    externalId: "demo_091",
    title: "Bursa Malaysia Hits 1,620 Points — Foreign Funds Return as Ringgit Strengthens",
    summary:
      "The FTSE Bursa Malaysia KLCI closed at 1,620.14 on Friday, the highest level since December 2014, as foreign funds recorded net purchases of RM1.2 billion in May so far on improving ringgit outlook and strong corporate earnings from banking and technology counters. Finance stocks led gains with CIMB up 4.2% and Maybank up 3.8% on the week.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/bursa-1620-foreign-funds-return-ringgit-strengthens",
    topic: "Finance & Investing",
    publishedAt: "2026-05-11T17:30:00+08:00",
  },
  {
    externalId: "demo_092",
    title: "ASB Dividend Confirmed at 4.5 Sen for 2024 — Plus 0.5 Sen Bonus for Members Below 55",
    summary:
      "Amanah Saham Nasional declared a 4.5 sen per unit dividend for Amanah Saham Bumiputera for 2024, in line with analyst expectations, plus an additional 0.5 sen bonus distribution for members aged 54 and below with accounts held for at least two years. Dividends will be credited by 15 June with total payouts reaching RM12.8 billion to 10.6 million ASB account holders.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/asb-dividend-4-5-sen-2024-bonus-under-55",
    topic: "Finance & Investing",
    publishedAt: "2026-05-11T10:30:00+08:00",
  },
  {
    externalId: "demo_093",
    title: "Government Retail Bond Offering: 4.2% Yield for 3 Years, RM200 Minimum, Open to All Malaysians",
    summary:
      "The Ministry of Finance opened subscriptions for a RM3 billion Government Retail Bond offering a fixed 4.2% annual interest rate for a 3-year tenure, with a minimum investment of RM200 and maximum RM1 million per individual, accessible through all Malaysian commercial banks and Agrobank from 16 May 2025. The bonds are fully government-guaranteed and interest is paid semi-annually.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=2437700",
    topic: "Finance & Investing",
    publishedAt: "2026-05-10T09:00:00+08:00",
  },
  {
    externalId: "demo_094",
    title: "Capital Gains Tax FAQ Released — LHDN Clarifies Property and Shares Treatment from 2025",
    summary:
      "The Inland Revenue Board published a 48-question FAQ clarifying capital gains tax implementation for disposals of unlisted shares and foreign properties from 1 January 2025, confirming that gains on listed Bursa Malaysia stocks remain CGT-exempt while unlisted private company shares are taxed at 10% on net gains after indexation adjustments. Individuals must submit CGT returns through e-Borang within 60 days of asset disposal.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/capital-gains-tax-faq-lhdn-property-shares-2025",
    topic: "Finance & Investing",
    publishedAt: "2026-05-10T11:00:00+08:00",
  },
  {
    externalId: "demo_095",
    title: "IGB REIT and Pavilion REIT Report Strong Q1 2025 Occupancy Above 96% — Distribution Up",
    summary:
      "IGB Real Estate Investment Trust and Pavilion REIT both reported Q1 2025 occupancy rates above 96%, with IGB REIT's Mid Valley Megamall and Gardens Mall recording tenant sales growth of 8.4% year-on-year and Pavilion KL achieving 97.2% occupancy. Both REITs increased their quarterly distributions per unit by 5–7%, making them among the top performers in Bursa's REIT sector.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/igb-reit-pavilion-reit-q1-2025-occupancy-96pct-distribution",
    topic: "Finance & Investing",
    publishedAt: "2026-05-10T14:00:00+08:00",
  },

  // ─── STARTUPS (3 articles) ────────────────────────────────────────────────────
  {
    externalId: "demo_096",
    title: "Malaysian Startup Ecosystem Raises USD 180 Million in Q1 2025 — Fintech and HealthTech Lead",
    summary:
      "Malaysian startups raised a combined USD 180 million in Q1 2025 across 42 deals, up 28% from Q1 2024, with fintech accounting for USD 74 million and healthtech claiming USD 38 million according to Startup Genome's Southeast Asia report. Notable rounds include PayWatch's USD 21 million Series B for earned wage access and BookDoc Health's USD 15 million Series A for telemedicine expansion.",
    sourceName: "Tech in Asia",
    sourceUrl: "https://www.techinasia.com",
    articleUrl: "https://www.techinasia.com/malaysia-startup-ecosystem-usd180m-q1-2025-fintech-healthtech",
    topic: "Startups",
    publishedAt: "2026-05-10T08:30:00+08:00",
  },
  {
    externalId: "demo_097",
    title: "Cradle Fund Opens CIP500 Grant Applications — Up to RM500,000 for Product Startups",
    summary:
      "Cradle Fund Sdn Bhd opened the 2025 batch of its Cradle Investment Programme 500 (CIP500), offering pre-commercialisation grants of RM100,000–RM500,000 for Malaysian technology startups developing scalable software, hardware, or deeptech products for global markets. Applications close 30 June 2025 via the Cradle portal with a focus on AI, greentech, and medical devices in this cycle.",
    sourceName: "Tech in Asia",
    sourceUrl: "https://www.techinasia.com",
    articleUrl: "https://www.techinasia.com/cradle-fund-cip500-grant-applications-rm500k-2025",
    topic: "Startups",
    publishedAt: "2026-05-10T10:00:00+08:00",
  },
  {
    externalId: "demo_098",
    title: "Penang Startup Accelerator Opens Applications — RM1.5 Million in Funding for 10 Deeptech Teams",
    summary:
      "Penang Digital City's 2025 startup accelerator programme opens applications for its fifth cohort, offering 10 selected deeptech and agri-tech startups RM150,000 each in non-dilutive funding plus 16 weeks of mentoring, office space at Penang Digital City Hub, and guaranteed pitch sessions with regional VCs. Applications close 15 June for the programme running August–November 2025.",
    sourceName: "Tech in Asia",
    sourceUrl: "https://www.techinasia.com",
    articleUrl: "https://www.techinasia.com/penang-startup-accelerator-rm1-5m-10-deeptech-agri-2025",
    topic: "Startups",
    publishedAt: "2026-05-10T12:30:00+08:00",
  },

  // ─── GLOBAL NEWS (2 articles) ─────────────────────────────────────────────────
  {
    externalId: "demo_099",
    title: "US Federal Reserve Signals One Rate Cut Possible in Late 2025 — Markets Rally 1.8%",
    summary:
      "Federal Reserve Chair Jerome Powell indicated in Congressional testimony that a single quarter-point rate cut remains on the table for late 2025 if inflation continues its downward trajectory toward the 2% target, pushing US stock markets up 1.8% and weakening the US dollar index by 0.6%. The statement boosted emerging market currencies including the ringgit, which gained 0.4% to 4.38 per dollar.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com",
    articleUrl: "https://www.reuters.com/markets/us/fed-powell-signals-one-rate-cut-possible-late-2025",
    topic: "Global News",
    publishedAt: "2026-05-10T08:00:00+08:00",
  },
  {
    externalId: "demo_100",
    title: "ASEAN Summit Concludes with Digital Economy Framework — Malaysia Leads Initiative on Cross-Border Data",
    summary:
      "The 46th ASEAN Summit concluded in Kuala Lumpur with Malaysia championing the ASEAN Digital Economy Framework Agreement covering cross-border data flows, digital payments interoperability, and mutual recognition of digital identities across all ten member states. PM Anwar, as ASEAN Chair, secured agreement on a RM2 billion regional digital infrastructure fund with contributions from dialogue partners including Japan, South Korea, and the EU.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com",
    articleUrl: "https://www.reuters.com/world/asia-pacific/asean-summit-digital-economy-framework-malaysia-leads",
    topic: "Global News",
    publishedAt: "2026-05-10T16:00:00+08:00",
  },
];
