import type { RawArticle } from "@/lib/types";

export const DEMO_ARTICLES: RawArticle[] = [
  // Economy
  {
    externalId: "demo_eco_001",
    title: "Bank Negara holds OPR at 3.00% for fifth consecutive meeting",
    summary: "Bank Negara Malaysia kept the Overnight Policy Rate unchanged at 3.00% on Wednesday, citing stable domestic demand and manageable inflation. Economists expect rates to remain on hold through 2025 as global uncertainties persist.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/business/business-news/2025/05/07/bnm-holds-opr",
    topic: "Economy",
    publishedAt: new Date(Date.now() - 2 * 3600_000).toISOString(),
    impactScore: 80,
    profileTags: ["working adult", "Renting", "Looking to buy property"],
    demoSummary: "Bank Negara held the OPR at 3.00% for the fifth consecutive meeting, keeping borrowing costs stable.",
    demoImpact: "Your mortgage repayments stay unchanged — on a RM500,000 variable-rate loan, monthly payments remain at roughly RM2,200 for now.",
  },
  {
    externalId: "demo_eco_002",
    title: "Malaysia GDP grows 4.8% in Q1 2025, beating analyst forecasts",
    summary: "Malaysia's economy expanded 4.8% year-on-year in the first quarter of 2025, driven by strong exports and domestic consumption. The Department of Statistics said manufacturing and services sectors led the growth.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/business/news.php?id=gdp_q1_2025",
    topic: "Economy",
    publishedAt: new Date(Date.now() - 5 * 3600_000).toISOString(),
    impactScore: 60,
    profileTags: ["Business Owner", "Investor"],
    demoSummary: "Malaysia's economy grew 4.8% in Q1 2025, beating forecasts on strong exports and domestic consumption.",
    demoImpact: "Stronger economic growth signals a healthier job market — your employment prospects and salary negotiation leverage may improve in the months ahead.",
  },
  {
    externalId: "demo_eco_003",
    title: "Ringgit strengthens to 4.42 against US dollar on positive trade data",
    summary: "The ringgit appreciated to its strongest level in two months, trading at 4.42 against the US dollar on Thursday morning. Analysts attribute the gains to better-than-expected trade surplus figures and easing dollar strength.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/money/2025/05/15/ringgit-strengthens",
    topic: "Economy",
    publishedAt: new Date(Date.now() - 4 * 3600_000).toISOString(),
    impactScore: 55,
    profileTags: ["Business Owner", "Investor", "working adult"],
    demoSummary: "The ringgit strengthened to 4.42 against the US dollar, its best level in two months.",
    demoImpact: "Your imported goods and overseas purchases are cheaper — a USD100 item now costs roughly RM442 instead of RM460 from two months ago.",
  },
  {
    externalId: "demo_eco_004",
    title: "EPF dividend for 2024 announced at 6.10% for conventional savings",
    summary: "The Employees Provident Fund declared a dividend of 6.10% for conventional savings and 5.80% for Simpanan Shariah for 2024, totalling RM57.7 billion in payouts. This is the highest payout in five years.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/business/2025/02/20/epf-dividend-2024",
    topic: "Economy",
    publishedAt: new Date(Date.now() - 10 * 3600_000).toISOString(),
    impactScore: 95,
    profileTags: ["working adult", "Fresh Graduate", "Student"],
    demoSummary: "EPF declared a 6.10% dividend for conventional savings in 2024 — the highest payout in five years, totalling RM57.7 billion.",
    demoImpact: "Your EPF savings earn 6.10% this year — on a RM100,000 balance, that's RM6,100 credited directly to your account.",
  },

  // Finance & Investing
  {
    externalId: "demo_fin_001",
    title: "KLCI rises 0.8% as foreign funds return to Bursa Malaysia",
    summary: "The FTSE Bursa Malaysia KLCI climbed 12.4 points to close at 1,581 on Tuesday, as foreign investors turned net buyers for the third consecutive session. Banking and technology stocks led the gains.",
    sourceName: "The Edge",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/klci-rises-bursa",
    topic: "Finance & Investing",
    publishedAt: new Date(Date.now() - 6 * 3600_000).toISOString(),
    impactScore: 60,
    profileTags: ["Investor", "Business Owner"],
    demoSummary: "Bursa's KLCI rose 12.4 points to close at 1,581 as foreign investors turned net buyers for a third session.",
    demoImpact: "If you hold Malaysian equities or unit trusts, your portfolio value edged higher today — banking and technology funds posted the strongest gains.",
  },
  {
    externalId: "demo_fin_002",
    title: "Government scraps proposed capital gains tax on listed shares",
    summary: "Finance Minister confirmed the government has shelved plans to introduce a capital gains tax on shares listed on Bursa Malaysia following strong pushback from investors and industry groups. The decision is effective immediately.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/business/business-news/2025/05/10/cgt-scrapped",
    topic: "Finance & Investing",
    publishedAt: new Date(Date.now() - 8 * 3600_000).toISOString(),
    impactScore: 90,
    profileTags: ["Investor", "Business Owner", "working adult"],
    demoSummary: "The government shelved its proposed capital gains tax on Bursa-listed shares following strong investor pushback, effective immediately.",
    demoImpact: "You can sell shares on Bursa Malaysia without any capital gains tax — all profits from stock sales remain fully tax-free with immediate effect.",
  },

  // Malaysian Politics
  {
    externalId: "demo_pol_001",
    title: "Parliament passes Undi18 amendments allowing 18-year-olds to contest elections",
    summary: "Malaysian parliament approved amendments to the Elections Act to allow 18-year-olds to stand as candidates in elections, not just vote. The change is expected to take effect before the next state elections.",
    sourceName: "Malaysiakini",
    sourceUrl: "https://www.malaysiakini.com",
    articleUrl: "https://www.malaysiakini.com/news/undi18-amendments",
    topic: "Malaysian Politics",
    publishedAt: new Date(Date.now() - 12 * 3600_000).toISOString(),
    impactScore: 65,
    profileTags: ["Student", "Fresh Graduate"],
    demoSummary: "Parliament approved amendments allowing 18-year-olds to stand as election candidates, not just vote, before the next state elections.",
    demoImpact: "If you're between 18 and 21, you are now legally eligible to contest elections — a significant expansion of your civic rights.",
  },
  {
    externalId: "demo_pol_002",
    title: "Sarawak state election set for August 2025, EC confirms date",
    summary: "The Election Commission officially announced Sarawak's state election will be held on 23 August 2025, with nomination day on 9 August. Campaigning for 82 state seats is expected to be the most competitive since 2021.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=sarawak_election_2025",
    topic: "Malaysian Politics",
    publishedAt: new Date(Date.now() - 18 * 3600_000).toISOString(),
    impactScore: 50,
    profileTags: ["working adult"],
    demoSummary: "Sarawak's state election is confirmed for 23 August 2025, with nomination day on 9 August across 82 seats.",
    demoImpact: "If you're a registered Sarawak voter, mark 23 August 2025 on your calendar — check your polling details at SPR.gov.my now.",
  },

  // Tech & AI
  {
    externalId: "demo_tech_001",
    title: "Malaysia launches RM2.5 billion national AI fund to attract data centre investment",
    summary: "Prime Minister announced a RM2.5 billion National AI Fund to subsidise electricity costs for hyperscale data centres and attract global tech companies. Google, Microsoft and Nvidia are among the first recipients of facilitation letters.",
    sourceName: "The Edge",
    sourceUrl: "https://theedgemalaysia.com",
    articleUrl: "https://theedgemalaysia.com/article/national-ai-fund",
    topic: "Tech & AI",
    publishedAt: new Date(Date.now() - 3 * 3600_000).toISOString(),
    impactScore: 70,
    profileTags: ["Business Owner", "Investor", "working adult"],
    demoSummary: "Malaysia launched a RM2.5 billion National AI Fund to subsidise data centre electricity costs, with Google, Microsoft and Nvidia as first beneficiaries.",
    demoImpact: "Your job market in tech is set to expand — these hyperscale investments typically create thousands of local tech and operations roles over the next 2–3 years.",
  },
  {
    externalId: "demo_tech_002",
    title: "MCMC to regulate AI-generated deepfakes under updated Communications Act",
    summary: "The Malaysian Communications and Multimedia Commission announced it will gazette new rules requiring platforms to label AI-generated content and remove deepfake videos within 24 hours of a valid complaint. Fines of up to RM500,000 apply.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/nation/2025/05/12/mcmc-deepfakes",
    topic: "Tech & AI",
    publishedAt: new Date(Date.now() - 7 * 3600_000).toISOString(),
    impactScore: 55,
    profileTags: ["working adult", "Student"],
    demoSummary: "MCMC will require platforms to label AI-generated content and remove deepfakes within 24 hours, with fines up to RM500,000.",
    demoImpact: "You'll see AI-labelled content more clearly on social media — if you create online content, ensure any AI-generated material is properly disclosed to avoid penalties.",
  },
  {
    externalId: "demo_tech_003",
    title: "Grab launches AI-powered driver safety score — high-risk trips auto-cancelled",
    summary: "Grab Malaysia will roll out an AI safety scoring system starting June 1 that analyses driving patterns in real time. Drivers with a safety score below 60 for two consecutive trips will have automatic booking suspension for 24 hours.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/tech/2025/05/14/grab-ai-safety",
    topic: "Tech & AI",
    publishedAt: new Date(Date.now() - 9 * 3600_000).toISOString(),
    impactScore: 50,
    profileTags: ["working adult", "commuter"],
    demoSummary: "Grab Malaysia will auto-suspend drivers scoring below 60 on its new AI safety system for two consecutive trips, starting 1 June 2025.",
    demoImpact: "Your Grab booking may be cancelled more often by the safety system — if a driver is suspended mid-trip, request a new driver immediately.",
  },

  // Property
  {
    externalId: "demo_prop_001",
    title: "Median house price in Klang Valley hits RM620,000 — up 8% from last year",
    summary: "Property data firm Brickz reports that the median transacted price for a terraced house in the Klang Valley rose to RM620,000 in Q1 2025, an 8% year-on-year increase. Subang Jaya and Cheras recorded the highest price growth.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/property/property-news/2025/05/09/kv-house-prices",
    topic: "Property",
    publishedAt: new Date(Date.now() - 14 * 3600_000).toISOString(),
    impactScore: 85,
    profileTags: ["Looking to buy property", "Renting", "working adult"],
    demoSummary: "Median terraced house prices in the Klang Valley hit RM620,000 in Q1 2025, up 8% from a year ago.",
    demoImpact: "Your target property is now roughly RM50,000 more expensive than a year ago — delaying your purchase further will likely cost you more as prices continue rising.",
  },
  {
    externalId: "demo_prop_002",
    title: "My First Home Scheme expanded — loan ceiling raised to RM500,000",
    summary: "The government has expanded the My First Home Scheme, raising the maximum loan amount from RM350,000 to RM500,000 and extending eligibility to households earning up to RM10,000 per month. Applications open from 1 June 2025.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=myfirsthome_2025",
    topic: "Property",
    publishedAt: new Date(Date.now() - 22 * 3600_000).toISOString(),
    impactScore: 90,
    profileTags: ["Looking to buy property", "Fresh Graduate", "working adult"],
    demoSummary: "The My First Home Scheme raised its loan ceiling to RM500,000 for households earning up to RM10,000/month, opening 1 June 2025.",
    demoImpact: "If your household income is under RM10,000/month, you can now borrow RM150,000 more than before — applications open 1 June 2025.",
  },
  {
    externalId: "demo_prop_003",
    title: "Penang approves 3,000 affordable units in Batu Kawan — priced from RM250,000",
    summary: "The Penang state government greenlit a 3,000-unit affordable housing project in Batu Kawan, with prices starting at RM250,000 for a 900 sq ft unit. Priority ballot for local Penang residents opens in July.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/nation/2025/05/11/batu-kawan-housing",
    topic: "Property",
    publishedAt: new Date(Date.now() - 30 * 3600_000).toISOString(),
    impactScore: 75,
    profileTags: ["Looking to buy property", "Renting"],
    demoSummary: "Penang approved 3,000 affordable housing units in Batu Kawan from RM250,000, with a priority ballot for local residents opening in July.",
    demoImpact: "If you're a Penang resident, register for the priority ballot in July — units start at RM250,000 for a 900 sq ft home in Batu Kawan.",
  },

  // Fuel & Transport
  {
    externalId: "demo_fuel_001",
    title: "RON95 subsidy rationalisation to begin July 2025 — price rises RM0.40 to RM2.45",
    summary: "The government confirmed RON95 petrol subsidy rationalisation will proceed from 1 July 2025, raising the pump price to RM2.45 per litre (up from RM2.05). Targeted cash assistance of RM100/month will be credited to eligible B40 households via e-Kasih.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/news/nation/2025/05/13/ron95-rationalisation",
    topic: "Fuel & Transport",
    publishedAt: new Date(Date.now() - 1 * 3600_000).toISOString(),
    impactScore: 98,
    profileTags: ["Car owner", "Both", "working adult", "commuter"],
    demoSummary: "RON95 petrol price rises from RM2.05 to RM2.45 per litre from 1 July 2025 as subsidy rationalisation begins.",
    demoImpact: "If you fill a 40-litre tank weekly, your monthly fuel bill rises by RM64 — eligible B40 households receive RM100/month via e-Kasih to offset this.",
  },
  {
    externalId: "demo_fuel_002",
    title: "LRT3 Shah Alam line opens to public — 26 stations, free rides until June 30",
    summary: "The LRT3 line connecting Bandar Utama to Johan Setia officially opened on Wednesday with 26 stations spanning 37km. The government announced free rides for all passengers until 30 June 2025 to encourage ridership during the soft launch.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/malaysia/2025/05/15/lrt3-opens",
    topic: "Fuel & Transport",
    publishedAt: new Date(Date.now() - 2.5 * 3600_000).toISOString(),
    impactScore: 85,
    profileTags: ["commuter", "working adult", "Shah Alam"],
    demoSummary: "The LRT3 opened with 26 stations from Bandar Utama to Johan Setia across 37km, with free rides for all until 30 June 2025.",
    demoImpact: "If your commute passes through Shah Alam or Klang, you can ride the full LRT3 line for free until 30 June 2025 — saving on petrol and toll costs.",
  },
  {
    externalId: "demo_fuel_003",
    title: "Toll-free Hari Raya Haji period announced — NPE, SPRINT and DUKE waived",
    summary: "PLUS Malaysia and the Works Ministry confirmed tolls on NPE, SPRINT, DUKE and five other urban expressways will be waived from 5–7 June 2025 for Hari Raya Haji. Intercity highways including the North-South Expressway are excluded.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=toll_free_raya_haji",
    topic: "Fuel & Transport",
    publishedAt: new Date(Date.now() - 5 * 3600_000).toISOString(),
    impactScore: 70,
    profileTags: ["Car owner", "Both", "commuter"],
    demoSummary: "Tolls on NPE, SPRINT, DUKE and five other urban expressways are waived from 5–7 June 2025 for Hari Raya Haji.",
    demoImpact: "You save on toll charges on these urban expressways from 5–7 June 2025 — note that the North-South Expressway and intercity highways are not included.",
  },
  {
    externalId: "demo_fuel_004",
    title: "JPJ launches instant driving licence renewal via MyJPJ app — no more queues",
    summary: "The Road Transport Department now allows full driving licence renewal through the MyJPJ app, including payment and digital licence issuance within 5 minutes. The service is live for Class B2, D and DA licences; motorcycles and lorries follow in August.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/nation/2025/05/08/myjpj-renewal",
    topic: "Fuel & Transport",
    publishedAt: new Date(Date.now() - 16 * 3600_000).toISOString(),
    impactScore: 75,
    profileTags: ["Car owner", "Both", "commuter", "working adult"],
    demoSummary: "JPJ now allows instant driving licence renewal via the MyJPJ app in under 5 minutes, covering Class B2, D and DA licences.",
    demoImpact: "You can renew your driving licence from your phone without queuing — complete payment in MyJPJ and receive your digital licence within 5 minutes.",
  },
  {
    externalId: "demo_021",
    title: "Bursa Malaysia Hits 1,640 Points — Foreign Funds Return as Ringgit Strengthens",
    summary: "Bursa Malaysia's FBM KLCI index climbed to 1,640 points this week, the highest since 2018, driven by returning foreign institutional investors. Net foreign inflow reached RM2.1 billion in March 2025. Analysts from Kenanga and Maybank IB both raised their year-end targets to 1,700.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://www.theedgemarkets.com",
    articleUrl: "https://www.theedgemarkets.com/article/bursa-klci-1640-foreign-funds-march-2025",
    topic: "Finance & Investing",
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isVideo: false,
    impactScore: 78,
    profileTags: ["Investor", "Business Owner"],
    demoSummary: "Bursa's KLCI hit 1,640 points — the highest since 2018 — on RM2.1 billion in net foreign inflows in March 2025.",
    demoImpact: "Your Malaysian equity holdings are at their most valuable in seven years — Kenanga and Maybank IB both raised their year-end targets to 1,700.",
  },
  {
    externalId: "demo_022",
    title: "Cradle Fund Opens CIP500 Applications — Up to RM500,000 for Malaysian Startups",
    summary: "Cradle Fund Sdn Bhd has opened the CIP500 grant programme for Q2 2025, offering up to RM500,000 in non-dilutive funding for early-stage Malaysian startups. Priority sectors include agritech, healthtech, fintech, and climate tech. Application deadline is 30 April 2025 via cradle.com.my.",
    sourceName: "Tech in Asia",
    sourceUrl: "https://www.techinasia.com",
    articleUrl: "https://www.techinasia.com/cradle-cip500-grant-q2-2025-applications",
    topic: "Startups",
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isVideo: false,
    impactScore: 75,
    profileTags: ["Business Owner", "Self-Employed / Freelance"],
    demoSummary: "Cradle Fund opened CIP500 grant applications offering up to RM500,000 in non-dilutive funding, closing 30 April 2025.",
    demoImpact: "If you're building a startup in agritech, healthtech, fintech or climate tech, apply via cradle.com.my before 30 April 2025 for up to RM500,000 in free funding.",
  },
  {
    externalId: "demo_023",
    title: "US Fed Signals One Rate Cut in Late 2025 — Ringgit and Bursa Expected to Benefit",
    summary: "The US Federal Reserve signalled a single 25 basis point rate cut is likely in Q4 2025 during its March FOMC meeting. Malaysian economists expect this to attract further capital inflows into emerging markets including Malaysia, potentially pushing the Ringgit to 4.20–4.25 against the USD by year end.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com",
    articleUrl: "https://www.reuters.com/markets/us-fed-rate-cut-signal-march-2025",
    topic: "Global News",
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isVideo: false,
    impactScore: 70,
    profileTags: ["Investor", "Business Owner"],
    demoSummary: "The US Fed signalled one 25bp rate cut in Q4 2025, with economists forecasting the ringgit to strengthen to 4.20–4.25 by year-end.",
    demoImpact: "Your ringgit savings and USD-priced purchases may improve — a ringgit at 4.20 means you'd spend roughly RM200 less to buy USD1,000 compared to current rates.",
  },
  {
    externalId: "demo_024",
    title: "Proton e.MAS 7 EV Sales Cross 3,000 Units — Government Extends EV Import Duty Exemption",
    summary: "Proton's first electric vehicle the e.MAS 7 surpassed 3,000 units sold in Q1 2025, making it Malaysia's best-selling EV. The government simultaneously confirmed the EV import duty exemption is extended until end of 2026, keeping prices of competing EVs from BYD, Chery, and Tesla suppressed.",
    sourceName: "Free Malaysia Today",
    sourceUrl: "https://www.freemalaysiatoday.com",
    articleUrl: "https://www.freemalaysiatoday.com/category/nation/2025/03/09/proton-emas7-ev-duty-exemption-2026",
    topic: "Fuel & Transport",
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isVideo: false,
    impactScore: 76,
    profileTags: ["Car owner", "Both"],
    demoSummary: "Proton's e.MAS 7 crossed 3,000 units sold and the government extended EV import duty exemptions until end of 2026.",
    demoImpact: "You have until end of 2026 to buy an EV at duty-exempted prices — BYD, Chery and Tesla models remain competitively priced while the exemption holds.",
  },
  {
    externalId: "demo_025",
    title: "Parliament Passes Amended Anti-Money Laundering Act — Stricter Penalties for Businesses",
    summary: "Parliament passed amendments to the Anti-Money Laundering, Anti-Terrorism Financing and Proceeds of Unlawful Activities Act (AMLA) in March 2025. Corporate penalties increased tenfold to RM10 million per offence. Businesses with annual revenue above RM5 million must now appoint a designated compliance officer by January 2026.",
    sourceName: "Malay Mail",
    sourceUrl: "https://www.malaymail.com",
    articleUrl: "https://www.malaymail.com/news/malaysia/2025/03/13/amla-amendment-parliament-2025",
    topic: "Malaysian Politics",
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    isVideo: false,
    impactScore: 72,
    profileTags: ["Business Owner", "Investor"],
    demoSummary: "AMLA amendments raised corporate penalties to RM10 million per offence; businesses above RM5M revenue must appoint a compliance officer by January 2026.",
    demoImpact: "If your business earns over RM5 million annually, you must appoint a dedicated compliance officer by January 2026 or risk penalties up to RM10 million per offence.",
  },
  {
    externalId: "demo_026",
    title: "HRDF Releases Full List of AI Upskilling Courses — Claimable Up to RM5,000 Per Employee",
    summary: "The Human Resources Development Fund released its 2025 approved AI and digital upskilling course list covering 847 programmes across 312 training providers. Employers can claim up to RM5,000 per employee per year. Popular claimable courses include Python for Data Science, Prompt Engineering, and Cloud Architecture fundamentals.",
    sourceName: "Bernama",
    sourceUrl: "https://www.bernama.com",
    articleUrl: "https://www.bernama.com/en/news.php?id=hrdf-ai-upskilling-courses-2025",
    topic: "Jobs & Career",
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isVideo: false,
    impactScore: 80,
    profileTags: ["Employed (Private)", "Employed (Government)", "Business Owner", "Fresh Graduate"],
    demoSummary: "HRDF released 847 approved AI and digital upskilling courses claimable up to RM5,000 per employee per year.",
    demoImpact: "Your employer can claim up to RM5,000 for you to enrol in AI courses like Python for Data Science or Prompt Engineering — ask your HR department to apply.",
  },
  {
    externalId: "demo_027",
    title: "Free HPV Vaccine Expanded to Boys Under 18 — Registration Opens April 2025",
    summary: "The Health Ministry announced the Human Papillomavirus (HPV) vaccine programme previously available only to girls is now extended to all boys under 18, provided free at all Klinik Kesihatan. The three-dose programme costs RM900 privately. Registration for school-based administration opens via MyHealth portal in April 2025.",
    sourceName: "CodeBlue",
    sourceUrl: "https://codeblue.galencentre.org",
    articleUrl: "https://codeblue.galencentre.org/2025/03/hpv-vaccine-boys-free-malaysia-2025",
    topic: "Health",
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isVideo: false,
    impactScore: 79,
    profileTags: ["Homemaker"],
    demoSummary: "Malaysia extended free HPV vaccination to all boys under 18 at Klinik Kesihatan, with school registration via MyHealth portal from April 2025.",
    demoImpact: "If you have a son under 18, register him for the free three-dose HPV vaccine via the MyHealth portal — this programme costs RM900 privately.",
  },
  {
    externalId: "demo_028",
    title: "Johor-Singapore Special Economic Zone Attracts RM15 Billion — 20,000 Jobs by 2027",
    summary: "The Johor-Singapore Special Economic Zone (JS-SEZ) has secured RM15 billion in confirmed investments from 43 companies in its first quarter of operations, targeting 20,000 direct jobs by 2027. Companies setting up in JS-SEZ qualify for a flat 15% corporate tax rate and a 10-year tax holiday for pioneer status industries.",
    sourceName: "The Star",
    sourceUrl: "https://www.thestar.com.my",
    articleUrl: "https://www.thestar.com.my/business/business-news/2025/03/07/johor-singapore-sez-rm15-billion-2025",
    topic: "Property",
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    isVideo: false,
    impactScore: 77,
    profileTags: ["Investor", "Business Owner", "Johor"],
    demoSummary: "The Johor-Singapore SEZ secured RM15 billion in investments targeting 20,000 jobs by 2027, with a flat 15% corporate tax rate.",
    demoImpact: "If you're considering expanding a business, JS-SEZ offers a flat 15% corporate tax and 10-year tax holiday — 20,000 direct jobs are targeted by 2027.",
  },
  {
    externalId: "demo_029",
    title: "Malaysia's 5G Coverage Hits 80% of Populated Areas — DNB Opens Network to All Telcos",
    summary: "Digital Nasional Berhad announced 5G coverage now reaches 80% of Malaysia's populated areas as of Q1 2025, ahead of schedule. All major telcos including Maxis, Celcom, Digi, and U Mobile have completed 5G network sharing agreements. Consumer 5G plan pricing is expected to drop 15–25% by Q3 2025 due to increased competition.",
    sourceName: "Tech in Asia",
    sourceUrl: "https://www.techinasia.com",
    articleUrl: "https://www.techinasia.com/malaysia-5g-coverage-80-percent-dnb-2025",
    topic: "Tech & AI",
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    isVideo: false,
    impactScore: 74,
    profileTags: [],
    demoSummary: "Malaysia's 5G coverage reached 80% of populated areas in Q1 2025; consumer 5G plan prices are expected to drop 15–25% by Q3 2025.",
    demoImpact: "Your 5G mobile plan is likely to get 15–25% cheaper by Q3 2025 as Maxis, Celcom, Digi, and U Mobile compete on the shared DNB network.",
  },
  {
    externalId: "demo_030",
    title: "ASB Dividend 2024 Announced at 4.75 Sen — Bonus Dividend of 0.25 Sen Included",
    summary: "Amanah Saham Bumiputera declared a 2024 income distribution of 4.75 sen per unit plus a special bonus dividend of 0.25 sen, totalling 5.0 sen — the highest payout since 2019. With the maximum unit holding of 300,000 units, eligible holders receive up to RM15,000. Distributions are credited directly to unitholder accounts by 31 March 2025.",
    sourceName: "The Edge Markets",
    sourceUrl: "https://www.theedgemarkets.com",
    articleUrl: "https://www.theedgemarkets.com/article/asb-dividend-2024-475-sen-bonus",
    topic: "Finance & Investing",
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isVideo: false,
    impactScore: 82,
    profileTags: ["Investor"],
    demoSummary: "ASB declared a total payout of 5.0 sen per unit for 2024 — 4.75 sen income plus 0.25 sen bonus — the highest since 2019.",
    demoImpact: "Your ASB account earns 5.0 sen per unit this year — on the maximum 300,000 units, that's RM15,000 credited to your account by 31 March 2025.",
  },
];

console.log("Demo articles:", DEMO_ARTICLES.length);
